import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
title: {
  default: 'Next.js',  //default title for all pages
  template: '%s | Next.js', //dynamic title for all pages
  absolute: "Next.js", //absolute title for all pages
},
description: 'Generated by Next.js',
}

export default function RootLayout({
children,
}: {
children: React.ReactNode
}) {
return (
<html lang="en">

<body className="bg-gray-100 text-gray-900">
    <header className="bg-blue-100 h-20 flex flex-col items-space-between justify-center px-4">
        <nav className="flex justify-between items-center">
            <a href="/" className="text-2xl font-bold">
                Next.js
            </a>
            <a href="/" className="text-2xl font-bold">
                Docs
            </a>
        </nav>
    </header>

    <main className="p-4">
        {children}
    </main>

    <footer className="bg-blue-100 h-20 text-gray-900 text-center flex flex-col items-center justify-center">
        <p>&copy; 2023 Next.js</p>
    </footer>
</body>

</html>
)
}
